export default [
	{
		cuisine: 'Italian',
		title: 'Spaghetti with tomatoes and mushrooms',
		image: 'https://i.pinimg.com/564x/1a/f6/ad/1af6adf8f05a4c58dd69804b3b0c66e9.jpg',
		duration: '30 min',
		description: `just really enjoyed the book and Jessica's perspective. Perhaps I feel swept up in some sort of tide myself. Anyway. Erin made this chunky Greek salad with tomato halves, slices of cucumber, whole olives and feta cheese scattered throughout. It seemed so rustic but classic and I could have eaten the entire bowl.`,
		directions: 'Put the lentils into a large mixing bowl. Scoop out the seedy center and finely dice the cucumbers. Do the same with the tomatoes and red pepper. The smaller the dice, the easier to scoop with a cracker. Add them to the mixing bowl. Add the red onion, olives, parsley, oregano, salt, pepper flakes, olive oil and vinegar and stir to mix. Gently stir in the crumbled feta and taste for seasonings. ',
		ingredients: [
			'300 g macarrão espaguete integral cozido al dente',
			'3 colheres (sopa) de azeite de oliva extravirgem',
			'4 dentes de alho picados',
			'1 1/2 xícara (chá) de cogumelo shiitake fatiado',
			'1 1/2 xícara (chá) de cogumelo-de-paris',
			'20 tomate cereja cortados no meio',
			' sal pimenta-do-reino e tirinhas de pimenta dedo-de-moça a gosto',
			'salsa picada a gosto'
		],
		servings: 4,
	},
	{
		cuisine: 'Dessert',
		title: 'Strawberry and chocolate cake',
		image: 'https://i.pinimg.com/564x/fa/8a/d0/fa8ad08c0904457e0e15c24d84aa2d87.jpg',
		duration: '75 min',
		description: `just really enjoyed the book and Jessica's perspective. Perhaps I feel swept up in some sort of tide myself. Anyway. Erin made this chunky Greek salad with tomato halves, slices of cucumber, whole olives and feta cheese scattered throughout. It seemed so rustic but classic and I could have eaten the entire bowl.`,
		directions: 'Put the lentils into a large mixing bowl. Scoop out the seedy center and finely dice the cucumbers. Do the same with the tomatoes and red pepper. The smaller the dice, the easier to scoop with a cracker. Add them to the mixing bowl. Add the red onion, olives, parsley, oregano, salt, pepper flakes, olive oil and vinegar and stir to mix. Gently stir in the crumbled feta and taste for seasonings. ',
		ingredients: [
			'6 morangos',
			'12 marshmallows tamanho médio',
			'6 mini brownies',
			'calda de chocolate Hersheys'
		],
		servings: 2,
	},
	{
		cuisine: 'Healthy',
		title: 'Cajun Chicken with Coriander and Lime Rice',
		image: 'https://i.pinimg.com/564x/a5/4d/4d/a54d4d37522a76a67002fa25b8e51515.jpg',
		duration: '35 min',
		description: `just really enjoyed the book and Jessica's perspective. Perhaps I feel swept up in some sort of tide myself. Anyway. Erin made this chunky Greek salad with tomato halves, slices of cucumber, whole olives and feta cheese scattered throughout. It seemed so rustic but classic and I could have eaten the entire bowl.`,
		directions: 'Put the lentils into a large mixing bowl. Scoop out the seedy center and finely dice the cucumbers. Do the same with the tomatoes and red pepper. The smaller the dice, the easier to scoop with a cracker. Add them to the mixing bowl. Add the red onion, olives, parsley, oregano, salt, pepper flakes, olive oil and vinegar and stir to mix. Gently stir in the crumbled feta and taste for seasonings. ',
		ingredients: [
			'2 peitos de frango sem pele',
			'1 abacate',
			'1 cebola pequena',
			'1 punhado de Coriander',
			'1/2 pimenta verde',
			'1/2 pimenta vermelha',
			'1/2 pimenta amarela',
			'1 limao Zest',
			'1 colher de chá de Cajun',
			'1 e 1/2 colher de chá de azeite de oliva',
		],
		servings: 3,
	},
	{
		cuisine: 'Snacks',
		title: 'Perfect Bruschetta',
		image: 'https://i.pinimg.com/564x/22/f0/78/22f078f1c0d3f39f604cae30c27e9b0d.jpg',
		duration: '10 min',
		description: `just really enjoyed the book and Jessica's perspective. Perhaps I feel swept up in some sort of tide myself. Anyway. Erin made this chunky Greek salad with tomato halves, slices of cucumber, whole olives and feta cheese scattered throughout. It seemed so rustic but classic and I could have eaten the entire bowl.`,
		directions: 'Put the lentils into a large mixing bowl. Scoop out the seedy center and finely dice the cucumbers. Do the same with the tomatoes and red pepper. The smaller the dice, the easier to scoop with a cracker. Add them to the mixing bowl. Add the red onion, olives, parsley, oregano, salt, pepper flakes, olive oil and vinegar and stir to mix. Gently stir in the crumbled feta and taste for seasonings. ',
		ingredients: [
			'6 pães franceses',
			'6 tomates grandes',
			'Salsa picada a gosto',
			'Pimenta do reino',
		],
		servings: 6,
	},
	{
		cuisine: 'Japanese',
		title: 'Sushi',
		image: 'https://i.pinimg.com/564x/52/c7/33/52c733b033e709cc4166c8b1090da1af.jpg',
		duration: '80 min',
		description: `just really enjoyed the book and Jessica's perspective. Perhaps I feel swept up in some sort of tide myself. Anyway. Erin made this chunky Greek salad with tomato halves, slices of cucumber, whole olives and feta cheese scattered throughout. It seemed so rustic but classic and I could have eaten the entire bowl.`,
		directions: 'Put the lentils into a large mixing bowl. Scoop out the seedy center and finely dice the cucumbers. Do the same with the tomatoes and red pepper. The smaller the dice, the easier to scoop with a cracker. Add them to the mixing bowl. Add the red onion, olives, parsley, oregano, salt, pepper flakes, olive oil and vinegar and stir to mix. Gently stir in the crumbled feta and taste for seasonings. ',
		ingredients: [
			'1 posta de salmão sem pele',
			'2 abacates',
			'300g arroz japonês',
			'4 folhas de alga',
		],
		servings: 2,
	}
];
